<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions targetNamespace="urn:com:horntvedt:case2:bestill:v1"
             name="Attestmottak" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:com:horntvedt:case2:bestill:v1"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema>
      <xsd:import namespace="urn:ske:ekstkom:mottak:attest:interfaces:provider:attestmottak:v1"
                  schemaLocation="../xsd/Bestilling.xsd"/>
    </xsd:schema>


  </types>
  <message name="bestillProdukt">
    <part name="bestillRequest" element="tns:BestillForespoersel"/>
  </message>

  <message name="bestillRespons">
    <part name="bestillRespons" element="tns:BestillRespons"/>
  </message>

  <!--<message name="iPlattformFeil">-->
    <!--<part name="fault" element="feil:iPlattformFeilElement"/>-->
  <!--</message>-->

  <portType name="Attestmottak">
    <operation name="bestillAttest">
      <input message="tns:bestillProdukt"/>
      <output message="tns:bestillRespons"/>

    </operation>
  </portType>

  <binding name="AttestmottakBinding" type="tns:Attestmottak">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="bestillAttest">
      <soap:operation
        soapAction="urn:ske:ekstkom:mottak:attest:interfaces:provider:attestmottak:v1/bestillAttest"/>
      <input>
        <soap:header message="tns:Brukskontekstinfo" part="brukskontekst" use="literal"/>
        <soap:body use="literal" parts="bestillRequest"/>
      </input>
      <output>
        <soap:body use="literal" parts="bestillRespons"/>
      </output>
      <fault name="fault">
        <soap:fault name="fault" use="literal"/>
      </fault>
    </operation>

  </binding>

  <service name="Attestmottak">
    <port name="Attestmottak" binding="tns:AttestmottakBinding">
      <soap:address location="http://localhost:8080/attestmottak/v1"/>
    </port>
  </service>
</definitions>

